version: '3.7'
services:
  app: 
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./src/:/var/www
    networks:
      - barber-system-app
  
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3307
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - barber-system-app

networks:
  barber-system-app:
    driver: bridge
volumes:
  dbdata:
    driver: local





